import { relations } from 'drizzle-orm';
import { boolean, index, integer, pgEnum, pgTable, serial, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

export const priorityEnum = pgEnum('priority', ['Low', 'Medium', 'High']);
export const syllabusStatusEnum = pgEnum('syllabus_status', ['Not Started', 'In Progress', 'Completed']);
export const dayEnum = pgEnum('day_of_week', ['MON', 'TUES', 'WED', 'THUR', 'FRI', 'SAT']);

export const users = pgTable('users', {
  id: serial('id').primaryKey(), username: text('username').notNull().unique(), passwordHash: text('password_hash').notNull(), displayName: text('display_name').notNull(), createdAt: timestamp('created_at').defaultNow().notNull(),
}, (table) => ({ usernameIdx: uniqueIndex('users_username_idx').on(table.username) }));
export const sessions = pgTable('sessions', { id: text('id').primaryKey(), userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), expiresAt: timestamp('expires_at').notNull() }, (table) => ({ userIdx: index('sessions_user_idx').on(table.userId) }));
export const tasks = pgTable('tasks', { id: serial('id').primaryKey(), userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), title: text('title').notNull(), description: text('description').default(''), category: text('category').notNull(), priority: priorityEnum('priority').default('Medium').notNull(), dueDate: timestamp('due_date'), completed: boolean('completed').default(false).notNull(), createdAt: timestamp('created_at').defaultNow().notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull() }, (table) => ({ userIdx: index('tasks_user_idx').on(table.userId) }));
export const subjects = pgTable('subjects', { id: serial('id').primaryKey(), userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), name: text('name').notNull(), color: text('color').default('#E85D82').notNull(), createdAt: timestamp('created_at').defaultNow().notNull() });
export const syllabusUnits = pgTable('syllabus_units', { id: serial('id').primaryKey(), subjectId: integer('subject_id').references(() => subjects.id, { onDelete: 'cascade' }).notNull(), name: text('name').notNull(), createdAt: timestamp('created_at').defaultNow().notNull() });
export const syllabusTopics = pgTable('syllabus_topics', { id: serial('id').primaryKey(), unitId: integer('unit_id').references(() => syllabusUnits.id, { onDelete: 'cascade' }).notNull(), topic: text('topic').notNull(), description: text('description').default(''), notes: text('notes').default(''), status: syllabusStatusEnum('status').default('Not Started').notNull(), targetDate: timestamp('target_date'), updatedAt: timestamp('updated_at').defaultNow().notNull() });
export const timetableEntries = pgTable('timetable_entries', { id: serial('id').primaryKey(), userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), dayOfWeek: dayEnum('day_of_week').notNull(), startTime: text('start_time').notNull(), endTime: text('end_time').notNull(), subject: text('subject'), type: text('type').default('class').notNull(), room: text('room'), notes: text('notes'), createdAt: timestamp('created_at').defaultNow().notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull() }, (table) => ({ dayIdx: index('timetable_day_idx').on(table.userId, table.dayOfWeek) }));
export const notes = pgTable('notes', { id: serial('id').primaryKey(), userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), title: text('title').notNull(), content: text('content').notNull(), category: text('category').default('General').notNull(), pinned: boolean('pinned').default(false).notNull(), createdAt: timestamp('created_at').defaultNow().notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull() });
export const routineItems = pgTable('routine_items', { id: serial('id').primaryKey(), userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), label: text('label').notNull(), completed: boolean('completed').default(false).notNull(), sortOrder: integer('sort_order').default(0).notNull(), createdAt: timestamp('created_at').defaultNow().notNull() });

export const userRelations = relations(users, ({ many }) => ({ tasks: many(tasks), timetable: many(timetableEntries), notes: many(notes), routine: many(routineItems) }));
export const subjectRelations = relations(subjects, ({ many }) => ({ units: many(syllabusUnits) }));
export const unitRelations = relations(syllabusUnits, ({ one, many }) => ({ subject: one(subjects, { fields: [syllabusUnits.subjectId], references: [subjects.id] }), topics: many(syllabusTopics) }));
