// 100 sweet, uplifting, romantic one-line push quotes crafted for Preethi 💗
export const PREETHI_100_QUOTES: string[] = [
  "Good morning, my love! You bring warmth, brilliance, and grace to every class you teach.",
  "Remember to breathe and smile—your hard work is shaping young minds so beautifully.",
  "Sending you the biggest hug before your day begins, Baby. You've got this!",
  "The classroom is lucky to have your passion, and I am the luckiest to have your heart.",
  "Take it one concept, one class, and one cup of tea at a time today, Preethi.",
  "Your dedication inspires everyone around you, especially me. Love you endlessly!",
  "Walk in with your lovely head held high—you are a phenomenal teacher and a wonderful soul.",
  "Just a tiny reminder between classes: you are deeply loved, appreciated, and cherished.",
  "May your lectures be smooth, your students be attentive, and your heart be light today.",
  "No matter how busy the schedule gets, remember your Dummu is always in your corner cheering for you.",
  "You don't have to be superhuman today, Baby—just being your caring self is more than enough.",
  "Thinking about your gorgeous smile right now. Can't wait to see it tonight!",
  "Every student you teach today carries a spark of your kindness into the world.",
  "Drink water, take a breather in the staff room, and never forget how proud I am of you.",
  "You turn complex physics into pure magic for your students, my brilliant girl.",
  "Here’s your daily reminder that you are my favorite person in the entire world. 💗",
  "Whatever challenges come today, your patience and intellect can solve them with ease.",
  "Even on hectic days, your grace shines brighter than anything else in the room.",
  "Sending you invisible kisses between your morning periods. Have a peaceful day!",
  "Teaching is hard work, but you do it with so much poise and heart.",
  "I hope today brings you funny student moments, easy concepts, and sweet little victories.",
  "You are capable of doing amazing things, and you prove it every single day, Preethi.",
  "Don’t let a single stressful moment steal the joy of what you’ve built, my sunshine.",
  "A quick love alert: someone at home loves you more than words could ever describe.",
  "Your calm energy is contagious—your students are blessed to learn from you.",
  "May your afternoon pass swiftly and smoothly so you can come home to rest.",
  "Be proud of the effort you put in today, even the invisible moments no one else sees.",
  "You make the world better just by being in it, Preethi. Go shine today!",
  "Whenever you feel tired, close your eyes for ten seconds and feel my arms around you.",
  "You're not just teaching lessons—you're building confidence in young minds.",
  "Good day, my beautiful teacher! May your energy stay high and your stress stay zero.",
  "Just checking in with a heart full of love for the hardest-working woman I know.",
  "Physics may explain gravity, but nothing explains how deeply I fell for you.",
  "You bring sunlight into every room you step into. Don't forget that today.",
  "One day at a time, one syllabus portion at a time—you are right on track, Preethi.",
  "Sending you an extra boost of love and peaceful momentum for your afternoon classes.",
  "I admire your passion and gentle strength more than you'll ever know.",
  "Your happiness means the world to me. Keep that sweet smile on your face today.",
  "Don't worry about perfection; your sincerity and warmth are what truly matter.",
  "You've handled every busy week before, and you will sail through this one too!",
  "A million little thoughts today, and every single one of them leads back to you.",
  "I hope your tea break is quiet, warm, and gives you the exact refresh you need.",
  "To the world, you might be a teacher, but to your students and to me, you're a hero.",
  "Keep your spirits high today, Baby—you have a heart of gold and a mind of diamonds.",
  "If anyone can make tough topics look simple and elegant, it's you, Preethi.",
  "Sending you good vibes, clear thoughts, and boundless love for today's lab practicals.",
  "Remember that you are cherished beyond measure, every hour of every day.",
  "May your day be filled with 'aha!' moments from your students and gentle peace in your soul.",
  "I believe in you with all my heart, even on days when your energy feels low.",
  "Your kindness leaves an indelible mark on every life you touch, my love.",
  "Take things gently today. Your health, peace of mind, and smile come first.",
  "Every time you teach, you're lighting a lamp for someone's future. Keep glowing!",
  "A little reminder that you are deeply adored by your number one fan—Dummu.",
  "Breathe in calm, breathe out any hurry. You are doing wonderfully today.",
  "You are smart, resilient, beautiful, and so incredibly loved.",
  "I hope someone tells you today how much they appreciate your dedication and care.",
  "No formula in physics could calculate how much I love you, Preethi.",
  "May your classroom be filled with curiosity, warmth, and respectful smiles today.",
  "Whenever you need a little courage, remember I’m always holding your hand in spirit.",
  "You are the heart of our home and the star of your classroom. Keep shining!",
  "Don't rush through the day, my love—savor the small wins and sweet moments.",
  "You make hard things look effortless, but I know how much love you put into your work.",
  "A warm virtual hug coming your way right now to power you through your next session.",
  "Your passion for teaching is one of the thousand reasons I fell in love with you.",
  "Stay calm, stay hydrated, and know that you are deeply cherished.",
  "May your chalk flow smoothly and your student doubts turn into brilliant understanding.",
  "You’re doing a magnificent job, Preethi. Never doubt the impact you make.",
  "I hope your day is as bright, warm, and beautiful as your smile.",
  "The world needs more teachers with your heart and intellect, my sweet love.",
  "Whenever the day feels heavy, remember how many obstacles you've already conquered.",
  "Just a quick whisper to remind you: I love you more and more every single day.",
  "You bring poise, intellect, and grace to everything your hands touch.",
  "Take a moment during lunch to truly relax and disconnect—you deserve the break.",
  "You are my pride, my peace, and my greatest blessing. Have a wonderful class today!",
  "Keep that sparkle in your eyes, Preethi; you inspire everyone around you.",
  "Every step you take today is moving your dreams forward. Keep going with pride.",
  "I love the passion you pour into teaching, and I love the tenderness in your heart.",
  "Sending you an avalanche of love to carry you through any afternoon fatigue!",
  "You are gifted, capable, and uniquely wonderful. Don't you forget it!",
  "May your lessons click effortlessly today and your students thank you with big smiles.",
  "Behind every great class is a teacher who cares—and you care with your whole heart.",
  "Thinking of your laughter right now. Wishing you a day full of cheerful moments!",
  "You have an extraordinary mind and an even more extraordinary heart, Preethi.",
  "Treat yourself kindly today; you are carrying so much with such quiet grace.",
  "A sweet love push: you are the prettiest, smartest, most loving wife in the world.",
  "Focus on what you can finish today, leave the rest for tomorrow, and smile for me.",
  "Your patience is unmatched, your enthusiasm is contagious, and your heart is pure gold.",
  "May today bring you light steps, clear thoughts, and lots of reasons to feel accomplished.",
  "I hope you know how much your hard work means to me and how proud I feel of you.",
  "You're not just delivering a syllabus—you are inspiring human hearts.",
  "Sending you a pocketful of love, sunshine, and peaceful energy for your classes.",
  "You turn ordinary moments into treasured memories, both in school and at home.",
  "Stand tall, smile wide, and let your brilliance lead the way today, Baby.",
  "Never forget: Dummu's favorite part of the day is when you come back home to me.",
  "You are stronger than any stressful deadline and sweeter than any morning breeze.",
  "I wish I could drop by your staff room with your favorite coffee and a big hug right now.",
  "May your students feel your dedication and rise to their highest potential today.",
  "Take pride in how far you’ve come, Preethi. You are doing something truly noble.",
  "Whatever happens today, our love is always a safe, warm harbor waiting for you.",
  "Good luck with all your classes today, my angel. You are loved beyond all measure! 💗"
];

// Helper to pick a random quote (optionally excluding current)
export function getRandomPreethiQuote(excludeQuote?: string): string {
  const filtered = excludeQuote
    ? PREETHI_100_QUOTES.filter((q) => q !== excludeQuote)
    : PREETHI_100_QUOTES;
  const list = filtered.length > 0 ? filtered : PREETHI_100_QUOTES;
  const index = Math.floor(Math.random() * list.length);
  return list[index];
}
